version: "3.1"

services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    
    # Salvando dados do banco caso o container seja apagado
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_PASSWORD=adm
      - POSTGRES_DB=ignicaodb

  app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  prisma:
    build: .
    container_name: prisma
    restart: always
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev"

